import { Cutive_Mono, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";

const cutive = Cutive_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-cutive",
  display: "swap",
});

const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ibmplex",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cutive.variable} ${ibmPlexMono.variable} antialiased`}>

        <Navbar />
        {children}
      </body>
    </html>
  );
}
